language:
  - cpp

sudo:
  - false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3

      # python3-pip package is not available, use 'easy_install3':
      # * https://github.com/travis-ci/apt-package-whitelist/issues/768
      - python3-setuptools # easy_install3

      # https://github.com/travis-ci-tester/travis-test-clang-cxx-11
      - libstdc++-4.8-dev

      # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
      - g++-4.8

matrix:
  include:
    - os: linux
    - os: osx

install:
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

script:
  - python3 --version
  - python3 ./test.py
